export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: '0.4rem',
  },
  font: {
    family:
      "Circular Std Book, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    xbold: 700,
    xxbold: 800,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.4rem',
      xxlarge: '2.8rem',
      xxxlarge: '3rem',
      xxxxlarge: '4rem',
      xxxxxlarge: '6rem',
    },
  },
  colors: {
    primary: '#023C8D',
    description: '#919191',
    descriptionLight: '#B2B2B2',
    white: '#FFFFFF',
    placeholder: '#C3C3C3',
    gray: '#A7A7A7',
    lightGray: '#EEEEEE',
    lightBlue: '#01BFDF',
    pink: '#DE8E85',
    boxShadow: '#00000029',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  button: {
    normal: '13rem',
    large: '25rem',
  },
}
